# Baddy Agent & CLAUD Configuration
# You can override these with environment variables as well.

claud_sync_endpoint: "https://your-cloud-endpoint/api/sync"
claud_upgrade_endpoint: "https://your-cloud-endpoint/api/version"
notify_email: "admin@example.com"
smtp_server: "smtp.gmail.com"
smtp_port: 465
smtp_password: "your-email-password"
notify_slack_webhook: "https://hooks.slack.com/services/..."
notify_teams_webhook: "https://outlook.office.com/webhook/..."
error_threshold: 3
health_check_interval: 600  # seconds
max_tasks_per_cycle: 20
# File locations
usage_file: "src/ai_agent/command_usage.json"
audit_file: "src/ai_agent/audit.log"
task_queue_file: "src/ai_agent/task_queue.json"
openai_api_key: "sk-..."  # Your OpenAI API key for NLP and self-build
# Web dashboard
enable_dashboard: true
# Port for FastAPI dashboard
dashboard_port: 8080
# Plugins and self-upgrade
github_repo: "https://github.com/youruser/yourrepo.git"
plugins_dir: "src/ai_agent/plugins"
# AWS/GCP integration
aws_sns_arn: "arn:aws:sns:us-east-1:123456789012:YourTopic"
gcp_pubsub_topic: "projects/your-project/topics/your-topic"
# Add more config options as needed, e.g.:
# notify_email: "admin@example.com"
# notify_slack_webhook: "https://hooks.slack.com/services/..."
# max_tasks_per_cycle: 20 

# Log Integration Configuration

# Google Drive Settings
google_drive_enabled: true
google_drive_folder_id: ""  # Add your Google Drive folder ID here

# Dropbox Settings
dropbox_enabled: true
dropbox_access_token: ""  # Add your Dropbox access token here

# Njanja.net Integration
njanja_net_webhook: ""  # Add your Njanja.net webhook URL here

# Log Settings
log_retention_days: 30
log_sync_interval_minutes: 60

# System Monitoring
monitor_cpu_threshold: 80  # Alert if CPU usage exceeds 80%
monitor_memory_threshold: 85  # Alert if memory usage exceeds 85%
monitor_disk_threshold: 90  # Alert if disk usage exceeds 90%

# Notification Settings
notify_on_error: true
notify_on_warning: true
notify_on_system_alert: true

# Cloud Sync Settings
sync_on_startup: true
sync_on_shutdown: true
sync_on_error: true
sync_on_warning: true

# Summary Generation
include_system_stats: true
include_command_history: true
include_error_details: true
include_warning_details: true 