name: Baddy Agent CI

on:
  push:
    branches: [main]
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Confirm CI Works

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Confirm Environment
        run: |
          echo "Python version:"
          python --version
          echo "CI execution successful for Baddy Agent
