name: Baddy Agent CI

on:
  push:
    branches: [main]
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  verify:
    name: Confirm CI Works
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "Dependencies not required or already satisfied"

      - name: Confirm Environment
        run: |
          echo "Python version:"
          python --version
          echo "CI execution successful for Baddy Agent"
