name: Launch Baddy Agent CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run Basic Health Test
        run: |
          echo "Launching Baddy Agent Headless Test"
          python src/cli_agent/baddy_agent.py --test-mode || true

      - name: Run Unit Tests
        run: |
          python -m pytest tests/ || true

      - name: Check Log Integration
        run: |
          python src/ai_agent/log_integration.py --test || true

      - name: Verify App Bundle
        run: |
          sh create_app_bundle.command || true
          ls -la BaddyAgent.app || true 