name: Deploy SecondBrain

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app awscli
          
      - name: Build app
        run: |
          chmod +x deploy.sh
          ./deploy.sh
          
      - name: Upload to S3 and GitHub
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./deploy.sh --upload
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/SecondBrainApp_Package.zip
            dist/SecondBrainApp_Package.sha256
            dist/version.txt
          body: |
            SecondBrain Release ${{ github.ref_name }}
            
            This release includes:
            - Phantom Core integration
            - Enhanced security features
            - Voice control capabilities
            - Blockchain integration
            
            See CHANGELOG.md for full details. 